### ISSUE TITLE
On file composer.json, about authors

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/noso-faucet#13]
Hey Andrii (@pasichDev)

If you have a closer look the block for authors is in the plural, as in "authors" not "author".

So you don't have to put yourself and me on the same entry:
```yaml
    "authors": [
        {
            "name": "Gustavo Carreno / Andrii Pasichnik",
            "email": "guscarreno@gmail.com"
        }
    ]
```

I think you can do it like this:
```yaml
    "authors": [
        {
            "name": "Andrii Pasichnik",
            "email": "YOU-EMAIL@example.com"
        },
        {
            "name": "Gustavo Carreno",
            "email": "guscarreno@gmail.com"
        }
    ]
```

And please, I'll always be second on the list. You're the one doing all the work. I'm just the guy bitching over your shoulder on how to do it LOL :rofl: :zany_face: 

Cheers,
Gus
